// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SharedKernel.Persistence;

#nullable disable

namespace SharedKernel.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001012449_RemoveCrossModuleForeignKeys")]
    partial class RemoveCrossModuleForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Album", "catalog");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Artist", "catalog");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("varchar(70)");

                    b.Property<string>("City")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Company")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Fax")
                        .HasColumnType("varchar(24)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(24)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("State")
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("SupportRepId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SupportRepId");

                    b.ToTable("Customer", "administration");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("varchar(70)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Fax")
                        .HasColumnType("varchar(24)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(24)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ReportsTo")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ReportsTo");

                    b.ToTable("Employee", "administration");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Genre", "administration");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddress")
                        .HasColumnType("varchar(70)");

                    b.Property<string>("BillingCity")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("BillingCountry")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("BillingPostalCode")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("BillingState")
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoice", "orders");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("TrackId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TrackId");

                    b.ToTable("InvoiceLine", "orders");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.MediaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("MediaType", "administration");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Playlist", "catalog");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.PlaylistTrack", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.HasKey("PlaylistId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("PlaylistTrack", "catalog");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<int?>("Bytes")
                        .HasColumnType("integer");

                    b.Property<string>("Composer")
                        .HasColumnType("varchar(220)");

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer");

                    b.Property<int?>("MediaTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("Milliseconds")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("GenreId");

                    b.HasIndex("MediaTypeId");

                    b.ToTable("Track", "catalog");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Album", b =>
                {
                    b.HasOne("SharedKernel.Persistence.Entities.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Customer", b =>
                {
                    b.HasOne("SharedKernel.Persistence.Entities.Employee", "SupportRep")
                        .WithMany("Customers")
                        .HasForeignKey("SupportRepId");

                    b.Navigation("SupportRep");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Employee", b =>
                {
                    b.HasOne("SharedKernel.Persistence.Entities.Employee", "ReportsToNavigation")
                        .WithMany("InverseReportsToNavigation")
                        .HasForeignKey("ReportsTo");

                    b.Navigation("ReportsToNavigation");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.InvoiceLine", b =>
                {
                    b.HasOne("SharedKernel.Persistence.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("InvoiceId");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.PlaylistTrack", b =>
                {
                    b.HasOne("SharedKernel.Persistence.Entities.Playlist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .IsRequired();

                    b.HasOne("SharedKernel.Persistence.Entities.Track", "Track")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("TrackId")
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Track", b =>
                {
                    b.HasOne("SharedKernel.Persistence.Entities.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Artist", b =>
                {
                    b.Navigation("Albums");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Employee", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("InverseReportsToNavigation");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceLines");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Playlist", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("SharedKernel.Persistence.Entities.Track", b =>
                {
                    b.Navigation("PlaylistTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
