<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1707;CS8620</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Administration\Admin.Module\Admin.Module.csproj" />
    <ProjectReference Include="..\..\src\Modules\Music\Music.Module\Music.Module.csproj" />
    <ProjectReference Include="..\..\src\Modules\Orders\Orders.Module\Orders.Module.csproj" />
    <ProjectReference Include="..\..\src\Shared\SharedKernel\SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\Shared\SharedKernel.Persistence\SharedKernel.Persistence.csproj" />
  </ItemGroup>

</Project>
