// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reporting.Modules.Data;

#nullable disable

namespace Reporting.Module.Data.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reporting.Modules.Domain.IntegrityFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MissingReference")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceSchema")
                        .IsRequired()
                        .HasColumnType("varchar(63)");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasColumnType("varchar(63)");

                    b.HasKey("Id");

                    b.HasIndex("CheckName", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("IX_IntegrityFinding_Open")
                        .HasFilter("\"ResolvedAt\" IS NULL");

                    b.ToTable("IntegrityFinding", "reporting");
                });

            modelBuilder.Entity("Reporting.Modules.Domain.InvoiceLineWithNamesRow", b =>
                {
                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("InvoiceLineId")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("TrackId")
                        .HasColumnType("integer");

                    b.Property<string>("TrackName")
                        .HasColumnType("text");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);

                    b.ToView("invoice_lines_with_names", "reporting");
                });

            modelBuilder.Entity("Reporting.Modules.Domain.SalesByGenreRow", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("GenreName")
                        .HasColumnType("text");

                    b.Property<long>("TrackCount")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitsSold")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("sales_by_genre", "reporting");
                });
#pragma warning restore 612, 618
        }
    }
}
