<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Shared\SharedKernel\SharedKernel.csproj"/>
        <ProjectReference Include="..\..\..\Shared\SharedKernel.Persistence\SharedKernel.Persistence.csproj"/>
    </ItemGroup>

</Project>
